### ISSUE TITLE
0.12.0 release schedule

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#226]
Here's a partial list of things to include in 0.12.0:
- [x] Drew-Dickerson DNA dodecamer test system (#223)
- [x] ContextCache bugfix and optimization (#235)
- [x] Compress serialized state strings (#232)
- [ ] remove unnecessary `parmed` use (#224)
- [ ] fix ideal gas failures (#225)
- [ ] Abl:imatinib test systems (#227)

Please edit to add other features/fixes for this release.

**Comment by jchodera** [comment]
How about we aim to cut this release on Friday?

**Comment by Lnaden** [comment]
@andrrizzi and I both agreed this and a YANK cut are slated for this Friday

**Comment by Lnaden** [comment]
I don't think we will get those back 3 issues in by tomorrow. Do you think we should instead cut a 0.11.1 for the first 3 today, leave this issue open and get the 0.12.0 cut when the back 3 issues get in?

**Comment by Lnaden** [comment]
The main reason for the release today is so we can properly test the compression and ContextCache fixes in YANK to keep the YANK release on track for this week as well

**Comment by andrrizzi** [comment]
Sounds good to me! I don't have time to tackle the other 3 items as well this week.

**Comment by andrrizzi** [comment]
Duplicate of #243 .
