### ISSUE TITLE
0.13.0 release schedule

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#243]
These items got bumped from 0.12.0 (#226):

- [ ] remove unnecessary `parmed` use (#224)
- [ ] fix ideal gas failures (#225)
- [ ] Abl:imatinib test systems (#227)

**Comment by andrrizzi** [comment]
I don't think we released 0.12.0 yet. We ended up calling it 0.11.1 since we didn't break backwards compatibility.

**Comment by jchodera** [comment]
I thought we had decided .z releases (for x.y.z) were exclusively bugfix releases, not for anything that added new features (.y).

Let's try to stick to this nomenclature.

**Comment by andrrizzi** [comment]
We used a mix I believe up to this point, because we can't use the major version to signal breaking of backwards compatibility until we release 1.0.

**Comment by jchodera** [comment]
> because we can't use the major version to signal breaking of backwards compatibility until we release 1.0.

Ah, excellent point.

**Comment by andrrizzi** [comment]
Added finalizing the API for reaction field to the list.
